services:
  - type: web
    name: sontha-web
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm run prisma:deploy && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production